import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://designs.hubtel.com/v4/smb///assets/css/main.css"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="body-wrapper" id="smb">
          <div id="internal-backoffice">
            <h4 className="text-center p-2 text-underline">USERS</h4>
            <div className="m-3 vh-height-100" id="scroll">
              <div>
                <div className="h-100 mx-5">{children}</div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
